// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Strict singleton pattern for Supabase client
const createSupabaseClient = () => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    }
  });
};

// Use globalThis to ensure the instance persists across HMR and module reloads
const globalSupabase = globalThis as any;

if (!globalSupabase.__supabase_instance__) {
  globalSupabase.__supabase_instance__ = createSupabaseClient();
}

export const supabase = globalSupabase.__supabase_instance__;